check_interval_seconds = 60
telegram_token = "topsecrettoken"
telegram_chat_id = 123456789
failure_threshold = 3
servers = [
    "http://example.com",
    "http://example.org",
    "http://example.net",
]